# Generated by Django 3.0.6 on 2020-05-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('ethnicity', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('entry_year', models.DateField()),
                ('grade', models.CharField(max_length=1)),
                ('previously_attended', models.BooleanField()),
                ('year_attended', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(choices=[(1, 1), (2, 2)], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city_2', models.CharField(blank=True, max_length=10, null=True)),
                ('state_2', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date_2', models.DateField(blank=True, null=True)),
                ('end_date_2', models.DateField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=20)),
                ('street_address_line_2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=5)),
                ('home_phone', models.CharField(max_length=13)),
                ('cell_phone', models.CharField(max_length=13)),
                ('p_street_address', models.CharField(blank=True, max_length=20, null=True)),
                ('p_street_address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('p_city', models.CharField(blank=True, max_length=10, null=True)),
                ('p_state', models.CharField(blank=True, max_length=10, null=True)),
                ('p_zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('p_home_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('p_cell_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('g_street_address', models.CharField(blank=True, max_length=20, null=True)),
                ('g_street_address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('g_city', models.CharField(blank=True, max_length=10, null=True)),
                ('g_state', models.CharField(blank=True, max_length=10, null=True)),
                ('g_zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('g_home_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('g_cell_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_first_name', models.CharField(max_length=50)),
                ('doc_last_name', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('insurance_cover', models.CharField(max_length=50)),
                ('health_info', models.TextField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('first_name_2', models.CharField(max_length=100)),
                ('last_name_2', models.CharField(max_length=100)),
                ('phone_2', models.CharField(max_length=13)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
