# Generated by Django 3.0.6 on 2020-05-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1),
        ),
    ]
